spring.application.name=ms-orders

server.port=8084

# Conexión a RDS — el endpoint se completa una vez creada la instancia en AWS
spring.datasource.url=jdbc:mysql://nexo-db.cg1wfibpbzep.us-east-1.rds.amazonaws.com:3306/orders_db?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Credenciales de RDS gestionadas por Secrets Manager
spring.config.import=aws-secretsmanager:nexo/rds/credentials

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ZoKCVBrHG

logging.level.com.nexo.msorders=INFO
logging.level.org.springframework.security=INFO

internal.api.key=nexo-internal-secret-2026-cambiar-en-produccion
server.error.include-message=always