spring.application.name=ms-orders

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/orders_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ZoKCVBrHG

logging.level.com.nexo.msorders=DEBUG
logging.level.org.springframework.security=DEBUG
internal.api.key=nexo-internal-secret-2026-cambiar-en-produccion
server.error.include-message=always

resilience4j.circuitbreaker.instances.tiendaService.sliding-window-size=10
resilience4j.circuitbreaker.instances.tiendaService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.tiendaService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.tiendaService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.tiendaService.ignore-exceptions=org.springframework.web.server.ResponseStatusException

resilience4j.circuitbreaker.instances.productoService.sliding-window-size=10
resilience4j.circuitbreaker.instances.productoService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productoService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.productoService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.productoService.ignore-exceptions=org.springframework.web.server.ResponseStatusException